<?xml version="1.0" encoding="utf-8"?><Database Name="bankcrm" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=KOMPUTER-STACJO;Initial Catalog=bankcrm;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="bankcrmConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.klienci" Member="klienci">
    <Type Name="klienci">
      <Column Name="id_klienci" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="imie" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="nazwisko" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[e-mail]" Member="e_mail" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="telefon" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="pesel" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="klienci_zadania" Member="zadania" ThisKey="id_klienci" OtherKey="id_klienci" Type="zadania" />
    </Type>
  </Table>
  <Table Name="dbo.zadania" Member="zadania">
    <Type Name="zadania">
      <Column Name="id_zadania" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tytul" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="tresc" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="autor_id_uzytkownicy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="id_klienci" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="termin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="klienci_zadania" Member="klienci" ThisKey="id_klienci" OtherKey="id_klienci" Type="klienci" IsForeignKey="true" />
      <Association Name="uzytkownicy_zadania" Member="uzytkownicy" ThisKey="autor_id_uzytkownicy" OtherKey="id_uzytkownicy" Type="uzytkownicy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.uzytkownicy" Member="uzytkownicy">
    <Type Name="uzytkownicy">
      <Column Name="id_uzytkownicy" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="haslo" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="imie" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="nazwisko" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="uprawnienia" Type="System.String" DbType="NChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="uzytkownicy_zadania" Member="zadania" ThisKey="id_uzytkownicy" OtherKey="autor_id_uzytkownicy" Type="zadania" />
    </Type>
  </Table>
</Database>